Repository WildCodeSchool/tours-php-2009-project3-mobilean, pull requests merged in 2021-01, with the labels that each got.

#5 Kevin us0 database
  migrations/Version20201216100633.php
  migrations/Version20201216102716.php
  migrations/Version20201218090846.php
  migrations/Version20210105132149.php
  src/Entity/RefillStation.php
  src/Entity/Vehicle.php
  src/Repository/RefillStationRepository.php
  src/Repository/VehicleRepository.php
Labels: changes done, reviewed

#11 Yann us2 vehicles
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/home.scss
  composer.lock
  public/assets/images/logo-mobilean.png
  templates/front/contact/contact.html.twig
  templates/front/contact/estimate.html.twig
  templates/front/contact/partner.html.twig
  templates/front/front_layout.html.twig
  templates/front/product/home.html.twig
Labels: changes done, reviewed

#13 Created connection of admin interface
  composer.json
  composer.lock
  config/packages/security.yaml
  migrations/Version20210105135623.php
  src/Controller/AdminController.php
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  templates/admin/admin_layout.html.twig
  templates/front/front_layout.html.twig
  templates/security/login.html.twig
Labels: reviewed

#21 Us 17 admin crud charging station
  composer.json
  composer.lock
  src/Controller/AdminController.php
  src/DataFixtures/RefillStationFixtures.php
  src/Form/RefillStationType.php
  templates/admin/charging_station_delete_form.html.twig
  templates/admin/charging_station_edit.html.twig
  templates/admin/charging_station_form.html.twig
  templates/admin/charging_station_new.html.twig
  templates/admin/charging_station_show.html.twig
  templates/admin/charging_stations.html.twig
Labels: review requested

#14 created form to let users ask for partnership
  src/Controller/ContactController.php
  src/DataClass/Partnership.php
  src/Form/PartnerType.php
  templates/front/contact/after_submit.html.twig
  templates/front/contact/partner.html.twig
Labels: changes done, reviewed

#22 Us 14 admin crud vehicle
  src/Controller/AdminController.php
  src/Controller/AdminProductController.php
  src/DataFixtures/VehicleFixtures.php
  src/Entity/RefillStation.php
  src/Entity/Vehicle.php
  src/Form/RefillStationType.php
  src/Form/VehicleType.php
  templates/admin/vehicle_delete_form.html.twig
  templates/admin/vehicle_edit.html.twig
  templates/admin/vehicle_form.html.twig
  templates/admin/vehicle_list.html.twig
  templates/admin/vehicle_new.html.twig
  templates/admin/vehicle_show.html.twig
  templates/admin/vehicles.html.twig
Labels: changes done, reviewed

#24 us2-vehicles
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/front-layout.scss
  assets/styles/home.scss
  assets/styles/vehicle.scss
  public/assets/images/arona3.jpg
  public/assets/images/arona4.jpg
  public/assets/images/caddy.jpg
  public/assets/images/car.png
  public/assets/images/daily.jpg
  public/assets/images/dailytransport.JPG
  public/assets/images/doblo panorama maxi.jpg
  public/assets/images/petrol.png
  src/Controller/ProductController.php
  templates/front/front_layout.html.twig
  templates/front/product/charging_stations.html.twig
  templates/front/product/home.html.twig
  templates/front/product/vehicle.html.twig
Labels: reviewed

#23 us6 estimate
  src/Controller/ContactController.php
  src/DataClass/EstimateIndividuals.php
  src/Form/EstimateIndividualsType.php
  src/Form/PartnerType.php
  templates/front/contact/after_submit.html.twig
  templates/front/contact/estimate.html.twig
Labels: changes done, reviewed

#25 Us6 estimate
  src/Controller/ContactController.php
  src/DataClass/EstimateCompanies.php
  src/Form/EstimateCompaniesType.php
  templates/front/contact/after_submit.html.twig
  templates/front/contact/estimate.html.twig
Labels: reviewed

#26 Bug fixed
  src/Controller/AdminController.php
  src/Controller/AdminProductController.php
  templates/admin/charging_station_delete_form.html.twig
  templates/admin/charging_station_edit.html.twig
  templates/admin/charging_station_new.html.twig
  templates/admin/charging_station_show.html.twig
  templates/admin/charging_stations.html.twig
  templates/admin/estimates.html.twig
  templates/admin/home.html.twig
  templates/admin/partners.html.twig
  templates/admin/vehicle_edit.html.twig
  templates/admin/vehicle_list.html.twig
  templates/admin/vehicle_new.html.twig
  templates/admin/vehicle_show.html.twig
Labels: review requested, reviewed

#29 Us21 partner notif
  .env
  README.md
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_snappy.yaml
  src/Controller/ContactController.php
  templates/email.html.twig
  templates/pdf.html.twig
Labels: reviewed

#30 Adding wkhtmltopdf install to Dockerfile
  Dockerfile
Labels: reviewed

#34 Design admin CRUD
  assets/js/app.js
  assets/styles/adminCrud.scss
  assets/styles/app.scss
  config/packages/twig.yaml
  templates/admin/charging_station_delete_form.html.twig
  templates/admin/charging_station_edit.html.twig
  templates/admin/charging_station_form.html.twig
  templates/admin/charging_station_new.html.twig
  templates/admin/charging_station_show.html.twig
  templates/admin/charging_stations.html.twig
  templates/admin/vehicle_delete_form.html.twig
  templates/admin/vehicle_edit.html.twig
  templates/admin/vehicle_form.html.twig
  templates/admin/vehicle_list.html.twig
  templates/admin/vehicle_new.html.twig
  templates/admin/vehicle_show.html.twig
Labels: reviewed

#31 us3-vehicles
  assets/styles/app.scss
  assets/styles/front-layout.scss
  assets/styles/home.scss
  assets/styles/vehicle.scss
  public/assets/images/logo.png
  src/Controller/ProductController.php
  templates/front/front_layout.html.twig
  templates/front/product/home.html.twig
  templates/front/product/vehicle.html.twig
Labels: reviewed

#36 Navbar
  .~lock.navbar responsive.odt#
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/front-layout.scss
  assets/styles/frontLayout.scss
  assets/styles/home.scss
  assets/styles/vehicle.scss
  navbar responsive.odt
  public/assets/images/arona3.jpg
  public/assets/images/arona4.jpg
  public/assets/images/caddy.jpg
  public/assets/images/daily.jpg
  public/assets/images/dailytransport.JPG
  public/assets/images/logoMobilean.png
  templates/front/front_layout.html.twig
Labels: reviewed

#39 navbar
  .~lock.navbar responsive.odt#
Labels: reviewed

#32 added basic contact form
  src/Controller/ContactController.php
  src/DataClass/Contact.php
  src/DataClass/EstimateCompanies.php
  src/DataClass/EstimateIndividuals.php
  src/DataClass/Partnership.php
  src/Form/ContactType.php
  src/Form/EstimateCompaniesType.php
  src/Form/EstimateIndividualsType.php
  src/Form/PartnerType.php
  templates/email.html.twig
  templates/front/contact/after_submit.html.twig
  templates/front/contact/contact.html.twig
  templates/pdf.html.twig
Labels: changes done, reviewed

#37 Us0 admin
  .gitignore
  src/Controller/AdminController.php
  src/Controller/ContactController.php
  src/DataClass/Contact.php
  src/Service/FileManager.php
  templates/admin/estimates.html.twig
  templates/admin/partners.html.twig
Labels: reviewed

#38 us0-VichRegul
  assets/styles/frontLayout.scss
  assets/styles/home.scss
  assets/styles/vehicle.scss
  navbar responsive.odt
  src/Controller/ProductController.php
  templates/front/front_layout.html.twig
  templates/front/product/home.html.twig
  templates/front/product/vehicle.html.twig
Labels: reviewed

#40 Us4 style
  assets/styles/refillStations.scss
  src/Entity/RefillStation.php
  src/Form/RefillStationType.php
  templates/front/product/charging_stations.html.twig
Labels: reviewed

#43 us0-general bug fix and unwanted files deletion
  public/assets/images/arona3.jpg
  public/assets/images/arona4.jpg
  public/assets/images/caddy.jpg
  public/assets/images/daily.jpg
  public/assets/images/dailytransport.JPG
  public/assets/images/doblo panorama maxi.jpg
  src/Controller/AdminController.php
Labels: reviewed

#44 us0-style
  assets/styles/frontLayout.scss
  assets/styles/home.scss
  public/assets/images/carLeaves.jpg
  public/assets/images/environnemental.jpg
  templates/front/product/home.html.twig
Labels: reviewed

#45 us0-intitial-user
  README.md
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/security/register_first_user.html.twig
Labels: reviewed

#46 us0-admin
  src/Controller/AdminController.php
  templates/admin/admin_layout.html.twig
  templates/admin/contact.html.twig
  templates/admin/estimates.html.twig
  templates/admin/home.html.twig
  templates/admin/partners.html.twig
Labels: reviewed

#47 us0-style
  assets/js/app.js
  assets/js/switchForm.js
  assets/styles/app.scss
  assets/styles/estimates.scss
  assets/styles/vehicle.scss
  templates/base.html.twig
  templates/front/contact/estimate.html.twig
  templates/front/contact/partner.html.twig
  templates/front/product/home.html.twig
  templates/front/product/vehicle.html.twig
  webpack.config.js
Labels: reviewed

#48 us9-partners PR
  config/packages/vich_uploader.yaml
  migrations/Version20210126144803.php
  src/Controller/AdminPartnersController.php
  src/Controller/ContactController.php
  src/Controller/FrontController.php
  src/Controller/InformationController.php
  src/Controller/ProductController.php
  src/Entity/Partner.php
  src/Entity/RefillStation.php
  src/Form/CurrentPartnerType.php
  src/Repository/PartnerRepository.php
  templates/admin/admin_layout.html.twig
  templates/admin/current_partner_delete_form.html.twig
  templates/admin/current_partner_edit.html.twig
  templates/admin/current_partner_form.html.twig
  templates/admin/current_partner_new.html.twig
  templates/admin/current_partner_show.html.twig
  templates/admin/current_partners.html.twig
  templates/front/front_layout.html.twig
Labels: reviewed

#49 Us 0 css navbar
  assets/styles/app.scss
  assets/styles/frontLayout.scss
  assets/styles/refillStations.scss
  src/Form/RefillStationType.php
  src/Form/VehicleType.php
  templates/admin/admin_layout.html.twig
  templates/admin/charging_station_new.html.twig
  templates/admin/vehicle_new.html.twig
  templates/front/front_layout.html.twig
  templates/front/product/vehicle.html.twig
Labels: reviewed

#50 typo generates error when there is a partner request pdf to display
  templates/admin/home.html.twig
Labels: bug fix, reviewed

#51 Us0 css
  assets/js/app.js
  assets/styles/estimates.scss
  assets/styles/home.scss
  assets/styles/partner.scss
  assets/styles/refillStations.scss
  assets/styles/vehicle.scss
  templates/front/contact/partner.html.twig
  templates/front/product/home.html.twig
  templates/front/product/vehicle.html.twig
Labels: reviewed

#52 us0-admin-navbar PR
  templates/admin/admin_layout.html.twig
Labels: reviewed

#53 fixed bug
  templates/front/product/vehicle.html.twig
Labels: bug fix, reviewed

#54 Us4 style
  assets/styles/refillStations.scss
  templates/front/product/charging_stations.html.twig
Labels: reviewed

#55 us10-legal PR
  migrations/Version20210127144050.php
  src/Controller/AdminLegalController.php
  src/Controller/ContactController.php
  src/Controller/InformationController.php
  src/Controller/ProductController.php
  src/Entity/LegalMention.php
  src/Form/LegalMentionType.php
  src/Repository/LegalMentionRepository.php
  templates/admin/home.html.twig
  templates/admin/legal_mention_delete_form.html.twig
  templates/admin/legal_mention_edit.html.twig
  templates/admin/legal_mention_form.html.twig
  templates/admin/legal_mention_new.html.twig
  templates/admin/legal_mention_show.html.twig
  templates/admin/legal_mentions.html.twig
  templates/front/information/legal.html.twig
Labels: reviewed

#59 error messages now in french
  src/DataClass/Contact.php
  src/DataClass/EstimateCompanies.php
  src/DataClass/EstimateIndividuals.php
  src/DataClass/Partnership.php
  src/Entity/LegalMention.php
  src/Entity/Partner.php
  src/Entity/RefillStation.php
  src/Entity/Vehicle.php
  src/Form/RefillStationType.php
  src/Form/VehicleType.php
Labels: reviewed

#61 Us 0 footer parteners
  assets/styles/app.scss
  assets/styles/frontLayout.scss
  assets/styles/home.scss
  assets/styles/vehicle.scss
  src/Form/CurrentPartnerType.php
  templates/admin/charging_station_show.html.twig
  templates/admin/charging_stations.html.twig
  templates/admin/current_partner_new.html.twig
  templates/admin/current_partner_show.html.twig
  templates/admin/current_partners.html.twig
  templates/admin/vehicle_list.html.twig
  templates/admin/vehicle_show.html.twig
  templates/base.html.twig
  templates/front/contact/after_submit.html.twig
  templates/front/contact/contact.html.twig
  templates/front/contact/estimate.html.twig
  templates/front/contact/partner.html.twig
  templates/front/front_layout.html.twig
  templates/front/information/about.html.twig
  templates/front/information/legal.html.twig
  templates/front/product/home.html.twig
  templates/front/product/vehicle.html.twig
  templates/security/login.html.twig
  templates/security/register_first_user.html.twig
Labels: changes done, reviewed

#62 Form style
  assets/styles/app.scss
  assets/styles/estimates.scss
  config/packages/twig.yaml
  templates/front/contact/contact.html.twig
  templates/front/contact/estimate.html.twig
  templates/front/contact/partner.html.twig
  templates/front/front_layout.html.twig
Labels: reviewed
